document.write('<section class="py-1 bg-light">')
document.write('<div class="container text-center">')
document.write('<h2 class="display-8 fw-bolder mb-4">Social media and contact</h2>')
document.write('<ul class="social list-inline">')
document.write('<li class="list-inline-item"><a target="_blank" href="mailto:vazquezborja@hotmail.es">                              <i class="fas fa-envelope fa-2x"></i></a></li>')
document.write('<li class="list-inline-item"><a target="_blank" href="https://www.instagram.com/borja__vazquez/">                   <i class="fab fa-instagram fa-2x"></i></a></li>')
document.write('<li class="list-inline-item"><a target="_blank" href="https://www.linkedin.com/in/borja-vazquez-713212175/">        <i class="fab fa-linkedin-in fa-2x"></i></a></li> ')
document.write('<li class="list-inline-item"><a target="_blank" href="https://open.spotify.com/playlist/2EFMkDAHvfgG0Si1NtwXBL">    <i class="fab fa-spotify fa-2x"></i></a></li>')
document.write('<li class="list-inline-item last-item"><a target="_blank" href="https://github.com/bovacu">                         <i class="fab fa-github-alt fa-2x"></i></a></li>')           
document.write('</ul> ')
document.write('</div>')
document.write('</section>')