document.write('<nav class="navbar navbar-expand-lg navbar-dark bg-dark">')
document.write('<div class="container px-5">')
document.write('<a class="navbar-brand" href="index.html"><img src="assets/logo256.png" width="64" height="64" alt="..." /></a>')
document.write('<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>')
document.write('<div class="collapse navbar-collapse" id="navbarSupportedContent">')
document.write('<ul class="navbar-nav ms-auto mb-2 mb-lg-0">')
document.write('<li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>')
document.write('<li class="nav-item"><a class="nav-link" target="_blank" href="documentation/index.html">Documentation</a></li>')
document.write('<li class="nav-item"><a class="nav-link" href="examples.html">Examples</a></li>')
document.write('<li class="nav-item"><a class="nav-link" href="faqSection.html">FAQ</a></li>')
document.write('<li class="nav-item"><a class="nav-link" href="store.html">Store</a></li>')
document.write('<li class="nav-item"><a class="nav-link" href="projectsIndex.html">About Me</a></li>')
document.write('</ul>')
document.write('</div>')
document.write('</div>')
document.write('</nav>')